version: "3"
services:
  # database:
  #   image: mongo:latest
  #   restart: always
  #   container_name: "mongo-container"
  #   ports:
  #     - 27017:27017
  #   networks:
  #     - my-network  

  rabbitmq:
    container_name: queue_service
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - my-network

  redis-server:
    container_name: redis
    image: 'redis:6.0.16'
    expose:
      - 6379
    networks:
      - my-network

  sender:
    image: sender
    container_name: sender-container
    ports:
      - 8082:8082
    depends_on:
      - rabbitmq
      - redis-server
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    networks:
      - my-network


  worker:
    image: worker
    container_name: worker-container
    ports:
      - 8081:8081
    depends_on:
      - rabbitmq
      - redis-server
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    networks:
      - my-network
    
  frontend:
    # image: ujjwalagarwal0575/frontend-image
    image: frontend
    container_name: frontend-container
    ports:
      - "3000:3000"
    networks:
      - my-network
    labels:
      kompose.service.type: LoadBalancer

networks:
  my-network:
    driver: bridge
