version: "3"
services:
  database:
    image: mongo:latest
    container_name: "mongo-container"
    ports:
      - 27017:27017
    networks:
      - my-network

  backend:
    # image: ujjwalagarwal0575/backend-image
    image: backend
    container_name: backend-container
    ports:
      - 8082:8082
    networks:
      - my-network

  frontend:
    # image: ujjwalagarwal0575/frontend-image
    image: frontend
    container_name: frontend-container
    ports:
      - "3000:3000"
    networks:
      - my-network
      
networks:
  my-network:
    driver: bridge
