apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: sender
  name: sender
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sender
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/my-network: "true"
        io.kompose.service: sender
    spec:
      containers:
        - env:
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
          image: sender
          name: sender-container
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          resources: {}
      restartPolicy: Always
status: {}
